### ISSUE TITLE
Staking

### ISSUE THREAD

**Issue by tdickman** [pengiundev/curve-vue#6]
The curve.fi interface offers 2 options, deposit, and deposit and stake. Deposit is clear, but deposit and stake is unclear. There is a link to "Manage staking in Mintr", but it just takes you to a website that references SNX.

What does it mean to stake?

**Comment by pengiundev** [comment]
Hey, sorry for the late reply. Deposit and stake does deposit and stake your received Curve LP tokens into the Synthetix rewards contracts.

You can learn more here for sBTC pool - https://medium.com/renproject/introducing-an-incentivized-btc-liquidity-pool-by-ren-synthetix-and-curve-213d21691d9a
